### ISSUE TITLE
Docker build BuildArg parameter doesn't seem right

### ISSUE THREAD

**Issue by jrouaix** [nuke-build/docker#4]
Hello here is a pointer to the issue I published to the wrong repos :

https://github.com/nuke-build/nuke/issues/166

**Comment by arodus** [comment]
It's indeed a bug. Will release a new version later today. Thanks :)

**Comment by arodus** [comment]
The new version was just published to NuGet, thanks for reporting the bug. 🎉

**Comment by jrouaix** [comment]
Working fine now, thank you for this lightspeed fix !
