### ISSUE TITLE
Docker settings do not implement abstract CustomLogger property

### ISSUE THREAD

**Issue by totollygeek** [nuke-build/docker#6]
The abstract property of ToolSettings `CustomLogger` is not implemented in the derived settings classes, therefor leading to an exception upon usage:
`Method 'get_CustomLogger' in type 'Nuke.Docker.DockerImagesSettings' from assembly 'Nuke.Docker, Version=0.2.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

**Comment by gliljas** [comment]
Got this too. I think this package just needs to be rebuilt with the latest Nuke core.

**Comment by arteven** [comment]
I've got the same error. Task:`DockerBuild();`
Versions:
Nuke.Common 0.17.6
Nuke.Docker 0.2.2

**Comment by matkoch** [comment]
Resolved.

@gliljas @gevlee please star the main repo!
